//! Write speech backends into `~/.pirs/config.toml` and optionally bootstrap a local daemon.

use std::path::PathBuf;
use std::process::Command;

use anyhow::{bail, Context};

#[derive(Debug, Clone)]
pub struct SetupOpts {
    pub cloud: bool,
    pub local: bool,
    pub local_url: String,
    pub force: bool,
}

pub fn run_setup(opts: SetupOpts) -> anyhow::Result<()> {
    let home = std::env::var("HOME").context("HOME not set")?;
    let config_path = PathBuf::from(&home).join(".pirs").join("config.toml");
    std::fs::create_dir_all(config_path.parent().unwrap())?;

    let mut text = if config_path.is_file() {
        std::fs::read_to_string(&config_path)?
    } else {
        String::new()
    };

    let has_speech_models = text.contains("alias = \"stt-default\"")
        || text.contains("caps = [\"stt\"]")
        || text.contains("caps = ['stt']");
    if has_speech_models && !opts.force {
        // Still allow re-printing status; only skip rewrite.
        eprintln!(
            "[speech setup] config already has speech models (pass --force to rewrite)\n  {}",
            config_path.display()
        );
    } else {
        // Strip previous managed block if force.
        if opts.force {
            text = strip_managed_speech_block(&text);
        }
        let block = build_speech_block(&opts)?;
        if !text.ends_with('\n') && !text.is_empty() {
            text.push('\n');
        }
        text.push_str(&block);
        std::fs::write(&config_path, text)?;
        println!("wrote speech config → {}", config_path.display());
    }

    if opts.local {
        bootstrap_local_daemon(&opts.local_url)?;
    }

    println!("\nResolved backends:");
    for line in pirs_ai::speech_status_lines() {
        println!("  {line}");
    }
    println!(
        "\nNext:\n  pirs-claw transcribe /path/to/audio.ogg\n  \
         # Telegram VN uses the same STT chain automatically\n  \
         # Optional TTS replies: PIRS_CLAW_TTS_ON_VOICE=1"
    );
    Ok(())
}

fn strip_managed_speech_block(text: &str) -> String {
    const BEGIN: &str = "# BEGIN pirs-speech-managed";
    const END: &str = "# END pirs-speech-managed";
    if let (Some(a), Some(b)) = (text.find(BEGIN), text.find(END)) {
        if b > a {
            let end = b + END.len();
            let mut out = String::new();
            out.push_str(&text[..a]);
            out.push_str(&text[end..].trim_start_matches('\n'));
            return out;
        }
    }
    text.to_string()
}

fn build_speech_block(opts: &SetupOpts) -> anyhow::Result<String> {
    let groq = std::env::var("GROQ_API_KEY")
        .ok()
        .filter(|s| !s.is_empty())
        .is_some();
    let openai = std::env::var("OPENAI_API_KEY")
        .ok()
        .filter(|s| !s.is_empty())
        .is_some();

    if opts.cloud && !groq && !openai && !opts.local {
        bail!(
            "no cloud STT keys found (GROQ_API_KEY / OPENAI_API_KEY). \
             Load ~/.pirs/secrets.env or pass --local for a daemon-only setup."
        );
    }

    let mut stt_serve: Vec<String> = Vec::new();
    let mut tts_serve: Vec<String> = Vec::new();
    let mut backends = String::new();

    if opts.local {
        backends.push_str(
            r#"
[[backends]]
name = "speech-local"
kind = "openai_compatible"
base_url = ""#,
        );
        backends.push_str(opts.local_url.trim_end_matches('/'));
        backends.push_str(
            r#""
"#,
        );
        stt_serve.push(r#"{ backend = "speech-local", model = "parakeet-tdt" }"#.into());
        tts_serve.push(r#"{ backend = "speech-local", model = "kokoro" }"#.into());
    }

    if opts.cloud && groq {
        backends.push_str(
            r#"
[[backends]]
name = "groq-speech"
kind = "openai_compatible"
base_url = "https://api.groq.com/openai/v1"
api_key_env = "GROQ_API_KEY"
"#,
        );
        stt_serve.push(
            r#"{ backend = "groq-speech", model = "whisper-large-v3-turbo" }"#.into(),
        );
    }

    if opts.cloud && openai {
        backends.push_str(
            r#"
[[backends]]
name = "openai-speech"
kind = "openai_compatible"
base_url = "https://api.openai.com/v1"
api_key_env = "OPENAI_API_KEY"
"#,
        );
        stt_serve.push(r#"{ backend = "openai-speech", model = "whisper-1" }"#.into());
        tts_serve.push(r#"{ backend = "openai-speech", model = "tts-1" }"#.into());
    }

    if stt_serve.is_empty() {
        bail!("nothing to configure for STT (need --cloud with keys and/or --local)");
    }

    let mut out = String::from("\n# BEGIN pirs-speech-managed\n");
    out.push_str("# Generated by `pirs-claw speech setup`. Re-run with --force to replace.\n");
    out.push_str(&backends);
    out.push_str("\n[[models]]\nalias = \"stt-default\"\ncaps = [\"stt\"]\nserve = [\n");
    for (i, s) in stt_serve.iter().enumerate() {
        out.push_str("  ");
        out.push_str(s);
        if i + 1 < stt_serve.len() {
            out.push(',');
        }
        out.push('\n');
    }
    out.push_str("]\n");

    if !tts_serve.is_empty() {
        out.push_str("\n[[models]]\nalias = \"tts-default\"\ncaps = [\"tts\"]\nserve = [\n");
        for (i, s) in tts_serve.iter().enumerate() {
            out.push_str("  ");
            out.push_str(s);
            if i + 1 < tts_serve.len() {
                out.push(',');
            }
            out.push('\n');
        }
        out.push_str("]\n");
    } else {
        out.push_str(
            "# (no TTS backend — add --local Kokoro or OPENAI_API_KEY for tts-1)\n",
        );
    }
    out.push_str("# END pirs-speech-managed\n");
    Ok(out)
}

fn bootstrap_local_daemon(local_url: &str) -> anyhow::Result<()> {
    let home = std::env::var("HOME").context("HOME not set")?;
    let dir = PathBuf::from(&home).join(".pirs").join("speech");
    std::fs::create_dir_all(&dir)?;

    let script = find_repo_helper().unwrap_or_else(|| dir.join("install_local_speech.sh"));
    if !script.is_file() {
        std::fs::write(
            &script,
            include_str!("../../../scripts/install_local_speech.sh"),
        )?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut p = std::fs::metadata(&script)?.permissions();
            p.set_mode(0o755);
            std::fs::set_permissions(&script, p)?;
        }
    }

    println!(
        "[speech setup] installing lightweight Rust pirs-audio\n  helper: {}\n  url: {local_url}\n  dir: {}",
        script.display(),
        dir.display()
    );

    let status = Command::new("bash")
        .arg(&script)
        .arg("--dir")
        .arg(&dir)
        .arg("--url")
        .arg(local_url)
        .status();
    match status {
        Ok(s) if s.success() => println!("[speech setup] pirs-audio install finished OK"),
        Ok(s) => eprintln!(
            "[speech setup] install exited {s} — cloud STT still works if configured"
        ),
        Err(e) => eprintln!("[speech setup] could not run install helper: {e}"),
    }

    try_start_pirs_audio(&dir, local_url);
    Ok(())
}

fn try_start_pirs_audio(dir: &std::path::Path, local_url: &str) {
    let run = dir.join("run.sh");
    if !run.is_file() {
        eprintln!("[speech setup] no {} yet — start pirs-audio manually after install", run.display());
        return;
    }
    // Probe health: http://host:port/v1 → http://host:port/health
    let base = local_url
        .trim_end_matches('/')
        .trim_end_matches("/v1")
        .to_string();
    let health = format!("{base}/health");
    if let Ok(out) = Command::new("curl")
        .args(["-sf", "--max-time", "1", &health])
        .output()
    {
        if out.status.success() {
            println!("[speech setup] pirs-audio already healthy at {health}");
            return;
        }
    }
    let log = dir.join("pirs-audio.log");
    let pid_path = dir.join("pirs-audio.pid");
    // background start
    let status = Command::new("bash")
        .arg("-c")
        .arg(format!(
            "nohup '{}' >>'{}' 2>&1 & echo $! >'{}'",
            run.display(),
            log.display(),
            pid_path.display()
        ))
        .status();
    match status {
        Ok(s) if s.success() => {
            println!(
                "[speech setup] started pirs-audio (pid file {}, log {})",
                pid_path.display(),
                log.display()
            );
        }
        Ok(s) => eprintln!("[speech setup] start pirs-audio exited {s}"),
        Err(e) => eprintln!("[speech setup] start pirs-audio: {e}"),
    }
}

fn find_repo_helper() -> Option<PathBuf> {
    let mut candidates = Vec::new();
    if let Ok(cwd) = std::env::current_dir() {
        let mut d = cwd;
        for _ in 0..6 {
            candidates.push(d.join("scripts/install_local_speech.sh"));
            if !d.pop() {
                break;
            }
        }
    }
    candidates.push(PathBuf::from(
        "/home/driver/xmoncode/pirs/scripts/install_local_speech.sh",
    ));
    candidates.into_iter().find(|p| p.is_file())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn strip_managed_block() {
        let t = "a\n# BEGIN pirs-speech-managed\nfoo\n# END pirs-speech-managed\nb\n";
        let s = strip_managed_speech_block(t);
        assert!(s.contains('a'));
        assert!(s.contains('b'));
        assert!(!s.contains("foo"));
    }

    #[test]
    fn build_cloud_groq_block() {
        // May or may not have keys in CI — just ensure function doesn't panic with cloud+local.
        let _ = build_speech_block(&SetupOpts {
            cloud: false,
            local: true,
            local_url: "http://127.0.0.1:8090/v1".into(),
            force: true,
        })
        .unwrap();
    }
}
